let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
    Plug 'tpope/vim-sensible'
	Plug 'alvan/vim-closetag'
    Plug 'scrooloose/nerdcommenter'
call plug#end()

" Write as sudo with :W
command W execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

" Remap command mode
nnoremap ; :

" Indent settings
set tabstop=4 softtabstop=4 expandtab shiftwidth=4 smarttab
" Line numbers
set number
" Enable mouse for all modes
set mouse=a
" Highlight current line
set cursorline

" Jump to last cursor position
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

colorscheme selenized_bw
set background=dark

