## My beets config
## The goods - path stuff!
paths:
  # Artist, The/{Singles, Remixes}/[Year] Album (Album Type)/{disc}/Track# Title
  default: |
    %the{$albumartist}/$albumslug/[$year] $album $albumtypes/$discslug/$track $title

item_fields:
  # This puts singles & remixes into their own folders
  albumslug: |
    t = {
      'single': 'Singles',
      'remix': 'Remixes'}
    return t[albumtype] if albumtype in t else ''
  # Cleaner versions of album types, displayed after an album's name
  albumtypes: |
    t = {
    'album': '(Album)',
    'ep': '(EP)',
    'soundtrack': '(OST)',
    'live': '(Live)',
    'compilation': '(Anthology)',
    'single': '',
    'remix': ''} # Blank because of $albumslug,

    return t[albumtype] if albumtype in t else albumtype
  discslug: |
    if disctotal > 1:
      s = f'CD {disc}'
      s += f' - {disctitle}' if disctitle else ''
      return s

## Everything else - boring
directory: /home/squigz/music/sorted/

per_disc_numbering: yes

import:
  move: yes
  from_scratch: yes

# Slightly modified from the defaults
# simply removes characters instead of replacing with _, allows :, replaces " with ', and replaces … with ...
# https://beets.readthedocs.io/en/stable/reference/config.html#replace
replace: {'[\\/]': '', ^\.: '', '[\x00-\x1f]': '', '[<>\?\*\|]': '', \.$: '', \s+$: '', ^\s+: '', ^-: '', '"': '''', '…': '...'}

## Plugin stuff
plugins: badfiles chroma convert discogs fetchart ftintitle inline lastgenre mbsync missing mpdupdate the scrub

lastgenre: # Add up to 3 genres with a minimum popularity of 20
  auto: yes
  count: 3
  min_weight: 20
fetchart: # HQ only pls
  auto: yes
  sources: coverart itunes amazon albumart # filesystem coverart itunes amazon albumart wikipedia google fanarttv lastfm
  cover_format: PNG
chroma: # Using AcoustID should be a last resort
  auto: no
# include: [acoustid.yaml] # This just has an AcoustID API key
