#!/bin/bash

MUSIC_DIR=/mnt/multi/media/music/

COVER=/tmp/cover.jpg

function reset_background
{
    # printf '\ePtmux;\e%s\e\\' "${\e]20;;100x100+1000+1000\a}"
    printf "\e]20;;100x100+1000+1000\a"
}

{
    album="$(mpc --format %album% current )"
    file="$(mpc --format %file% current )"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"

    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER" 
    if [[ -n "$src" ]] ; then
	convert "$src" -resize 700x "$COVER"
        if [[ -f "$COVER" ]] ; then
           #scale down the cover to 30% of the original
           # printf '\etmux;\e%s\e\\' "\e]20;${COVER};100x100+87+00:op=keep-aspect\a"
           printf "\e]20;${COVER};100x100+87+00:op=keep-aspect\a"
        else
            reset_background
        fi
    else
        reset_background
    fi
} &
